name: DxR

project:
    version: 1.0
    download_url: https://github.com/ronellsicat/DxR/raw/master/DxR.unitypackage

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

links:
    navigation:
      - title: Tutorials
        url: https://ronellsicat.github.io/DxR/site/tutorials.html
      - title: Documentation
        url: https://ronellsicat.github.io/DxR/site/documentation.html
      - title: Examples
        url: https://ronellsicat.github.io/DxR/site/examples.html
    header:
      - title: GitHub
        url: https://github.com/ronellsicat/DxR
    footer:
      - title: GitHub
        url: https://github.com/ronellsicat/DxR
      - title: Issues
        url: https://github.com/ronellsicat/DxR/issues?state=open

social:
    github:
        user: ronellsicat
        repo: DxR
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-111149380-1

disqus:
    shortname: dxr

markdown: kramdown

# Jekyll theme adapted from https://github.com/allejo/jekyll-docs-theme
